### ISSUE TITLE
Crashes with large list

### ISSUE THREAD

**Issue by sumgr0** [D4Vinci/bugz-tools#1]
The script crashes with the list of 5k domains.

python3 ~/BigIP_scanner.py xaa

         BigIP Scanner - By: Karim 'D4Vinci' Shoair

[+] Loaded 5000 domain(s)
 | Collecting results ( Total progress: 0.40%)Traceback (most recent call last):
  File "/home/sumit_grover/BigIP_scanner.py", line 131, in <module>
    main(args)
  File "/home/sumit_grover/BigIP_scanner.py", line 96, in main
    domain_result = site.result()
  File "/usr/lib/python3.7/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/usr/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/usr/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/sumit_grover/BigIP_scanner.py", line 31, in Big_man
    if no_detection or detect(url, heads):
  File "/home/sumit_grover/BigIP_scanner.py", line 25, in detect
    title = re.compile("title>(.*)</title").findall(req.content.decode())
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xcc in position 255: invalid continuation byte

**Comment by D4Vinci** [comment]
Just pushed a fix, it should fix it.
Check it out and tell me

**Comment by sumgr0** [comment]
It works now.. Thanks for the fix and for the tool...

Cheers!

**Comment by D4Vinci** [comment]
No problem, glad that fixed it :tada:

**Comment by sumgr0** [comment]
Now testing the limits :)

![image](https://user-images.githubusercontent.com/11391119/86823743-d5abc980-c0aa-11ea-89c2-bbd77f55bde2.png)
